### ISSUE TITLE
Cost values are required to be integers

### ISSUE THREAD

**Issue by GPHemsley** [dhgutteridge/Brew-Distance#2]
The original Text::Brew allows fractional costs, but this Python implementation forces cost values to be integers:

```
          not isinstance(cost[0], int) or not isinstance(cost[1], int) or
          not isinstance(cost[2], int) or not isinstance(cost[3], int)):
```

If this is just for type checking and not for another reason, `numbers.Number` or `numbers.Real` might be more appropriate. (The `numbers` module was introduced in 2.6, so compatibility shouldn't be a problem.)

**Comment by dhgutteridge** [comment]
Quite right, thanks for mentioning this. I've adjusted accordingly.

**Comment by GPHemsley** [comment]
Thank you!
